# coding: utf-8

"""
    Trakerr API

    Get your application events and errors to Trakerr via the *Trakerr API*.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import time
import unittest

from trakerr import Trakerr
from trakerr import TrakerrClient

class TestStackTraceLine(unittest.TestCase):
    """ StackTraceLine unit test stubs """

    def setUp(self):
        self.logger = Trakerr.get_logger("898152e031aadc285c3d84aeeb3c1e386735434729425", "Python", "newlogger")

    def tearDown(self):
        TrakerrClient.shutdown()

    def test_error(self):
        """
        Test error
        """
        time.sleep(3)

        #Built in python handler
        try:
            raise ArithmeticError("Exception")
        except:
            self.logger.exception("Corrupt file.")

def callback(response):
    """
    Callback method for the send_event_async function. Currently outputs nothing.
    :param response: message returned after the async call is completed.
    """
    pass


if __name__ == '__main__':
    unittest.main()
