# coding: utf-8

"""
    Trakerr API

    Get your application events and errors to Trakerr via the *Trakerr API*.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import trakerr_client
from trakerr_client.rest import ApiException
from trakerr_client.apis.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """ EventsApi unit test stubs """

    def setUp(self):
        self.api = trakerr_client.apis.events_api.EventsApi()

    def tearDown(self):
        pass

    def test_events_post(self):
        """
        Test case for events_post

        Submit an application event or error to Trakerr
        """
        pass


if __name__ == '__main__':
    unittest.main()
