language: python
python:
  - "2.7.9"
  - "3.4"
# command to install dependencies
# Make sure to change the branch name if you're not making a PR off the develop branch.
install: 
  - "pip install git+https://github.com/trakerr-com/trakerr-python.git"
# command to run tests
script: python test/test_send_event.py

notifications:
  email: false
  #Add slack notifications instead when slack comes back up.
  slack: trakerr:vrFTXvCHJrNvWsMHWg80gL5B
