# coding: utf-8

"""
    Trakerr API

    Get your application events and errors to Trakerr via the *Trakerr API*.

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
from six import iteritems
import re


class InnerStackTrace(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, type=None, message=None, trace_lines=None):
        """
        InnerStackTrace - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'type': 'str',
            'message': 'str',
            'trace_lines': 'StackTraceLines'
        }

        self.attribute_map = {
            'type': 'type',
            'message': 'message',
            'trace_lines': 'traceLines'
        }

        self._type = type
        self._message = message
        self._trace_lines = trace_lines

    @property
    def type(self):
        """
        Gets the type of this InnerStackTrace.


        :return: The type of this InnerStackTrace.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this InnerStackTrace.


        :param type: The type of this InnerStackTrace.
        :type: str
        """

        self._type = type

    @property
    def message(self):
        """
        Gets the message of this InnerStackTrace.


        :return: The message of this InnerStackTrace.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this InnerStackTrace.


        :param message: The message of this InnerStackTrace.
        :type: str
        """

        self._message = message

    @property
    def trace_lines(self):
        """
        Gets the trace_lines of this InnerStackTrace.


        :return: The trace_lines of this InnerStackTrace.
        :rtype: StackTraceLines
        """
        return self._trace_lines

    @trace_lines.setter
    def trace_lines(self, trace_lines):
        """
        Sets the trace_lines of this InnerStackTrace.


        :param trace_lines: The trace_lines of this InnerStackTrace.
        :type: StackTraceLines
        """

        self._trace_lines = trace_lines

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
